accelerator: mps
batch_size: 128
cosine_shift: 0.008
devices: 1
early_stopping_min_delta: 1.0e-05
early_stopping_patience: 15
encoder_dropout: 0.1
field_keys:
- c
final_filters: 1
in_channels: 4
input_size: 64
kernel_size: 3
learning_rate: 0.0001
log_every_n_steps: 50
max_epochs: 200
model_save_path: checkpoints/diffusion_heat/20260602_2135
num_timesteps: 500
optimiser: adamw
out_channels: 64
precision: 16
problem_type: wave
save_every_n_epochs: 10
training_data_path: data/train_data/wave_equation_m64_h1_t2_minmax_N400.pt
val_split: 0.1
wandb_entity: louis-godtfredsen
wandb_project: ml-for-pdes
wandb_run_name: null
